---
- debug:
    var: virtual_machines
  tags:
    - install_kvm

- name: "install qeme and libvrt related stuff"
  apt:
    name: [qemu-kvm, libvirt-clients, libvirt-daemon-system, bridge-utils, libvirt-dev]
    update_cache: true
    state: latest

- name: "install python modules"
  pip:
    name: [libvirt-python, lxml]

- name: "setup kvm directory"
  mount:
    path: /mnt/kvm
    src: "{{storage.device}}p1"
    fstype: ext4
    state: mounted

- name: "generate install iso"
  include_role:
    name: kickstartvm
  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine

- name: List remote VMs
  virt:
    command: list_vms
  register: vms_list
  tags:
    - install_kvm

- set_fact:
    vms_list: "{{vms_list.list_vms}}"
  tags:
    - install_kvm

- debug:
    var: vms_list

- include: undefine.yml
  tags:
    - never
    - drop_kvm

##
# this can take quite a while!
- name: "install virtual machine | {{inventory_hostname}}-{{virtual_machine.name}}"
  include_role:
    name: ansible-kvm
    apply:
      tags:
        - config_vms

  vars:
    kvm_images_path: /mnt/kvm

    kvm_virtual_networks:
      - name: "{{virtual_machine.network}}"
        mode: bridge
        bridge_name: "{{virtual_machine.network}}"
        autostart: true
        state: active
    kvm_vms:
      - name: "{{inventory_hostname}}-{{virtual_machine.name}}"
        autostart: true
        # Define boot devices in order of preference
        boot_devices:
          - hd
          - cdrom
        graphics: true
        # Define disks in MB
        disks:
          # ide, scsi, virtio, xen, usb, sata or sd
          - disk_driver: virtio
            name: "{{inventory_hostname}}-{{virtual_machine.name}}.disk"
            size: "{{virtual_machine.storage_size}}"

          # define a cdrom with a specific iso
          - disk_driver: qemu
            image: "{{git.directory}}/makeiso/{{inventory_hostname}}-{{virtual_machine.name}}.iso"
            cdrom: true

        # Define memory in MB
        memory: "{{virtual_machine.memory}}"
        network_interfaces:
          - source: "{{virtual_machine.network}}"
            network_driver: virtio
            type: bridge
        state: running
        vcpu: "{{virtual_machine.cpus}}"

    # Define KVM Dir type Storage Pools to create
    kvm_storage_pools:
      - name: kvms
        path: /mnt/kvm/
        autostart: true
        state: active

    kvm_config_storage_pools: true

    kvm_enable_libvirtd_syslog: true

    kvm_manage_vms: true

    # Defines if kvm/libvirt should be configured
    kvm_config: true

    # Defines if kvm_users should be added to libvirtd for managing KVM
    kvm_config_users: true

    # Defines if kvm virtual networks should be configured
    # if set to true ensu
    kvm_config_virtual_networks: true

  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine

  # only install if the vm does not exist already
  when: "inventory_hostname + '-' + virtual_machine.name not in vms_list"
  tags:
    - install_kvm

- name: "shutdown all vm's just in case they are not"
  virt:
    command: shutdown
    name: "{{inventory_hostname}}-{{virtual_machine.name}}"

  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine
  ignore_errors: true
  tags:
    - install_kvm

- name: "wait for the vm to shut down after install {{inventory_hostname}}-{{virtual_machine.name}}"
  virt:
    command: status
    name: "{{inventory_hostname}}-{{virtual_machine.name}}"
  register: vmstatus
  until: "'status' in vmstatus and vmstatus.status == 'shutdown'"
  delegate_to: "{{ inventory_hostname }}"
  retries: 1000
  delay: 5

  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine
  tags:
    - install_kvm

- name: start virtual machines
  virt:
    name: "{{inventory_hostname}}-{{virtual_machine.name}}"
    state: running
  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine
  tags:
    - install_kvm
    - generate_inventory
    -
- name: wait for vm to be up and running
  virt:
    name: "{{inventory_hostname}}-{{virtual_machine.name}}"
    command: status
    uri: "qemu:///session"
  register: result
  until: result.status == 'running'
  delay: 1
  retries: 1000
  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine
  tags:
    - install_kvm
    - generate_inventory

- name: generate list of configured and running virtual machines
  set_fact:
    deployed_vms: "{{ deployed_vms | default([]) + [{'name': inventory_hostname + '-' + virtual_machine.name, 'group' : virtual_machine.group}]}}"
  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine
  tags:
    - generate_inventory
  delegate_to: 127.0.0.1

- debug:
    var: deployed_vms
  tags:
    - generate_inventory
  delegate_to: 127.0.0.1

##
# this builds new environment files

- name: track installed KVMs and build a new inventory file
  when:  virtual_machine.group
  include_role:
    name: inventory
  vars:
    hostname: "{{inventory_hostname}}-{{virtual_machine.name}}"
    group: "{{virtual_machine.group}}"
  loop: "{{virtual_machines}}"
  loop_control:
    loop_var: virtual_machine
  tags:
    - generate_inventory
