---
- name: "deploying Ontology"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: ontology
    compose: "{{git.remote_directory}}/ontology/docker-compose.yml"
  tags:
    - deploy_ontology
