##
# configure the minimum system setup for us, in preparation of the deploying the actual cluster
##
- hosts: barebone
  gather_facts: True
  become_user: root
  become: true
  name: "minimum system setup"
  tasks:

    - import_role:
        name: network

    - import_role:
        name: default

    - name: "configure user accounts"
      include_role:
        name: users
      vars:
        user: "{{kvm_user}}"
      loop: "{{accounts.users}}"
      loop_control:
        loop_var: "kvm_user"
