---
- hosts: all
  gather_facts: True
  become_user: root
  become: true
  name: "gather facts accross all"

- hosts: node
  become_user: root
  become: true
  name: "install the barebone system layout"
  tasks:
    - name: "configure user accounts"
      include_role:
        name: users
      vars:
        user: "{{kvm_user}}"
      loop: "{{accounts.users}}"
      loop_control:
        loop_var: "kvm_user"

    - import_role:
        name: network

    - import_role:
        name: default

    - import_role:
        name: docker

    - import_role:
        name: drives

- hosts: kvm_node
  become_user: root
  become: true
  name: "install the actual kvm cluster"
  tasks:
    - import_role:
        name: kvm

- hosts: test_cluster
  become_user: root
  become: true
  name: "install the docker test cluster on top of the kvm cluster"
  tasks:
    - import_role:
        name: docker


- hosts: prod_cluster
  become_user: root
  become: true
  name: "install the docker test cluster on top of the kvm cluster"
  tasks:
    - import_role:
        name: docker
