- src: mrlesmithjr.netplan
- src: ypsman.ipv6_disable
- src: openmicroscopy.nfs-mount

- src: https://github.com/berlinguyinca/ansible-kvm.git
  version: master
  name: ansible-kvm

- src: https://github.com/berlinguyinca/ansible-tmux.git
  version: master
  name: ansible-tmux

- src: geerlingguy.ntp
- src: geerlingguy.docker
- src: geerlingguy.firewall
- src: geerlingguy.java
- src: geerlingguy.jenkins
- src: geerlingguy.postgresql

- src: https://github.com/NVIDIA/ansible-role-nvidia-docker
  version: master
  name: nvidia.docker

- src: davidwittman.redis

- src: https://github.com/berlinguyinca/ansible-spark-cluster.git
  version: master
  name: spark

- src: https://github.com/privacylabs/ansible-tunnel
  version: master
  name: ansible-tunnel

