- src: mrlesmithjr.netplan
- src: ypsman.ipv6_disable
- src: nickjj.docker
- src: atosatto.docker-swarm  
- src: openmicroscopy.nfs-mount

- src: https://github.com/berlinguyinca/ansible-kvm.git
  version: master
  name: ansible-kvm
