---
- hosts: all
  gather_facts: True
  become_user: root
  become: true

- hosts: kvm_vm_test_cluster
  tasks:
    - name: "configure user accounts"
      include_role:
        name: users
      vars:
        user: "{{kvm_user}}"
      loop: "{{accounts.users}}"
      loop_control:
        loop_var: "kvm_user"

    - import_role:
        name: network

    - import_role:
        name: default

    - import_role:
        name: docker

    - import_role:
        name: elk

    - import_role:
        name: monitoring

    - import_role:
        name: jenkins