---
- hosts: all
  gather_facts: True
  become_user: root
  become: true

# Clone docker-swarm-cluster repository locally first which will later be
# pushed to the manager nodes. Requires git ssh access to BitBucket repository
- hosts: 127.0.0.1
  connection: local
  tasks:
    - import_role:
        name: fiehnlab-utils/docker-swarm-repository-clone

- hosts: kvm_vm_test_cluster
  tasks:
    - name: "configure user accounts"
      include_role:
        name: users
      vars:
        user: "{{kvm_user}}"
      loop: "{{accounts.users}}"
      loop_control:
        loop_var: "kvm_user"

    - import_role:
        name: network

    - import_role:
        name: default

    - import_role:
        name: docker

#   - import_role:
#       name: elk
#     vars:
#       nfs_cluster: test
#       nfs_dir: logging_elasticsearch

    - import_role:
        name: monitoring

    #
    # Fiehn Lab service definitions
    #

    # Second step in updating docker swarm config on manager nodes
    - import_role:
        name: fiehnlab-utils/docker-swarm-repository-synchronize

    # Docker Swarm Proxy
    - import_role:
        name: fiehnlab/proxy

    # DevOps
    - import_role:
        name: fiehnlab/jenkins
      vars:
        # Note, mounting on the test mount is currently important
        nfs_cluster: test
        nfs_dir: jenkins

    - import_role:
        name: fiehnlab/mona
      vars:
        nfs_cluster: test
        nfs_dir: mona
