---

- name: "evaluate partitions"
  parted:
    device: "{{storage.device}}"
    unit: GiB
  register: nvme_info

- name: "remove partitions if layout is none expected"
  parted:
    device: "{{storage.device}}"
    number: "{{part.num}}"
    state: absent
  with_items: "{{nvme_info.partitions}}"
  when: nvme_info.partitions | length != 1
  loop_control:
    loop_var: part

- name: "define partition 1 for kvm storage"
  parted:
    device: "{{storage.device}}"
    number: 1
    state: present
    part_end: "0%"
    part_start: "99%"

- name: "format disk in ext4, if not done so"
  filesystem:
    dev: "{{storage.device}}p1"
    fstype: ext4
    force: False
