---

- name: "evaluate partitions"
  parted:
    device: "{{storage.device}}"
    unit: GiB
  register: nvme_info
  tags:
    - always
- name: "remove partitions if layout is none expected"
  parted:
    device: "{{storage.device}}"
    number: "{{ item.num }}"
    state: absent
  with_items:
    - "{{ nvme_info.partitions }}"
  tags:
    - force_reset
    - never

- name: "define partition 1 for kvm storage"
  parted:
    device: "{{storage.device}}"
    number: 1
    state: present
    part_end: "{{storage.split_kvm.end}}%"
    part_start: "{{storage.split_kvm.start}}%"

- name: "define partition 2 for gluster storage"
  parted:
    device: "{{storage.device}}"
    number: 2
    state: present
    part_end: "{{storage.split_gluster.end}}%"
    part_start: "{{storage.split_gluster.start}}%"

- name: "format disk in ext4, if not done so"
  filesystem:
    dev: "{{storage.device}}p1"
    fstype: ext4
    force: False


- name: "format disk in ext4, if not done so"
  filesystem:
    dev: "{{storage.device}}p2"
    fstype: ext4
    force: False
