---

##
# where do we want to store git checkout modules during the install stage
# these should NOT be ever deleted, you choose wisely
git:
  directory: "/mnt/git"

elk:
  ##
  # which fork do you want to use for the elk logstash
  repo: https://github.com/metabolomics-us/docker-elk.git
  deploy: true
