---
- name: "install required pip packages"
  pip:
    name: [jsondiff,pyyaml,docker]

- name: "install docker | install"
  block:
    - include_role:
        name: geerlingguy.docker
  tags:
    - swarm
    - destroy_swarm

- name: destroy swarm
  docker_swarm:
    state: absent
    force: true
  tags:
    - destroy_swarm
    - never

- set_fact:
    manager: "{{groups['docker_swarm_manager'][0]}}"
  tags:
    - always

- set_fact:
    manager_addr: "{{hostvars[manager]['ansible_ssh_host']}}"
  tags:
    - always
- debug:
    var: manager_addr
  tags:
    - always

- name: setup swarm | manager
  docker_swarm:
    state: present
    advertise_addr: "{{ docker.nic }}:4567"
    listen_addr: "{{ docker.nic }}:2377"
  tags:
    - swarm
  when:
    - "'docker_swarm_manager' in group_names"

- name: setup swarm | get token
  shell: docker swarm join-token -q worker
  register: docker_join_token_result
  when:
    - "'docker_swarm_manager' in group_names"
  tags:
    - swarm

- set_fact:
    docker_join_token: "{{docker_join_token_result['stdout']}}"
  tags:
    - swarm
  when:
    - "'docker_swarm_manager' in group_names"

- name: leave swarm | node
  docker_swarm:
    state: absent
  tags:
    - destroy_swarm
    - never

- name: setup swarm | node
  docker_swarm:
    state: join
    advertise_addr: "{{docker.nic}}:4567"
    remote_addrs: [ "{{manager_addr}}" ]
    join_token: "{{hostvars[groups['docker_swarm_manager'][0]].docker_join_token}}"
  tags:
    - swarm
  when:
    - "'docker_swarm_manager' not in group_names"

- name: "configure labels"
  when: "'docker_swarm_manager' in group_names and docker_node_labels is defined"
  docker_node:
    labels_state: merge
    hostname: "{{item.key}}"
    labels: "{{item.value}}"
  with_dict: "{{docker_node_labels}}"
  tags:
    - swarm
