---

- name: "install required pip packages"
  pip:
    name: [jsondiff,pyyaml,docker]


- import_role:
    name: "nickjj.docker"
  tags: ["docker"]

- name: "setup the docker swarm cluster"
  include_role:
    name: "atosatto.docker-swarm"
  vars:
    skip_engine: True # if true, skip the docker engine installation
    skip_group: True  # if true, does not add the docker_admin_users to the docker_group_name
    skip_swarm: False  # if true, skip the swarm setup
    skip_docker_py: True # if true, skip the docker-py

- name: "cloning monitoring stack"
  when: "'docker_swarm_manager' in group_names and docker.swarmprom.deploy == true"
  git:
    repo: "{{docker.swarmprom.repo}}"
    version: master
    dest: "{{git.directory}}/swarmprom"
    clone: true
    update: true

- name: "cloning logging stack"
  when: "'docker_swarm_manager' in group_names and docker.elk.deploy == true"
  git:
    repo: "{{docker.elk.repo}}"
    version: master
    dest: "{{git.directory}}/logging"
    clone: true
    update: true
- name: "configure labels"
  docker_node:
    labels_state: merge
    hostname: "{{item}}"
    labels: "{{ docker_node_labels }}"

  with_inventory_hostnames:
    - node

  when: "'docker_swarm_manager' in group_names"


- name: "deploying monitoring stack"
  when: "'docker_swarm_manager' in group_names and docker.swarmprom.deploy == true"
  docker_stack:
    state: present
    name: monitoring
    compose: "{{git.directory}}/swarmprom/docker-compose.yml"

- name: "deploying logging stack"
  when: "'docker_swarm_manager' in group_names and docker.elk.deploy == true"
  docker_stack:
    state: present
    name: logging
    compose: "{{git.directory}}/logging/docker-stack.yml"
          
