---
- name: install required software
  apt:
    name: [ dos2unix, p7zip-full, cpio, gzip, genisoimage, whois, pwgen, wget, fakeroot, isolinux, xorriso ]

- name: clone git
  git:
    repo: https://github.com/metabolomics-us/linux-unattended-installation.git
    version: master
    dest: "{{git.directory}}/makeiso"
    update: true
    clone: true
    force: true

- name: update permissions
  file:
    path: "{{git.directory}}/makeiso"
    mode: 0777
    recurse: true

- name: configure variables
  stat:
    path: "{{git.directory}}/makeiso/{{inventory_hostname}}-{{virtual_machine['name']}}.iso"
  register: iso_exists

- template:
    backup: true
    src: "preseed.cfg.j2"
    dest:  "{{git.directory}}/makeiso/ubuntu/18.04/custom/preseed.cfg"

- template:
    backup: true
    src: "build-iso.sh"
    dest:  "{{git.directory}}/makeiso/ubuntu/18.04/build-iso.sh"

- name: generate kickstart image
#  when: iso_exists == false
  shell: ./ubuntu/18.04/build-iso.sh
  become: true
  args:
    chdir: "{{git.directory}}/makeiso"
    executable: /bin/bash

