---
- name: install required software
  apt:
          name: [ dos2unix, p7zip-full, cpio, gzip, genisoimage, whois, pwgen, wget, fakeroot, isolinux, xorriso ]

- name: clone git
  git:
        repo: https://github.com/metabolomics-us/linux-unattended-installation.git
        version: master
        dest: /mnt/git/makeiso
        update: true 
        clone: true 
        force: true

- name: update permissions
  file:
          path: /mnt/git/makeiso
          mode: 0777
          recurse: true

- name: configure variables
  stat:
          path: /mnt/git/makeiso/ubuntu-18.04-netboot-amd64-unattended.iso
  register: iso_exists

- name: generate kickstart image
  when: iso_exists == false
  shell: ./ubuntu/18.04/build-iso.sh
  become: false
  args:
       chdir: /mnt/git/makeiso
       executable: /bin/bash

- debug:
        var: vm_to_install

- name: drop vm if exists
  vars:
          libvirt_vms:
                -state: absent
  ignore_errors: true

  include_role: 
       name: stackhpc.libvirt-vm
 
- name: create virtual machine       
  include_role: 
       name: stackhpc.libvirt-vm
  vars:
           libvirt_vms:
                   - state: present
                   - name: '{{vm_to_install.name}}'
                     memory_mb: "{{vm_to_install.memory}}"
                     vcpus: "{{vm_to_install.cpu}}"
                     volumes:
                             - name: 'data-{{vm_to_install.name}}'
                               device: 'disk'
                               capacity: '{{vm_to_install.storage_size}}GB'
                               pool: '{{vm_to_install.pool}}'
                     interfaces:
                             - network: '{{vm_to_install.network}}'

