---
- name: install required software
  apt:
    name: [ dos2unix, p7zip-full, cpio, gzip, genisoimage, whois, pwgen, wget, fakeroot, isolinux, xorriso ]

- name: clone git
  git:
    repo: https://github.com/metabolomics-us/linux-unattended-installation.git
    version: master
    dest: "{{git.directory}}/mnt/git/makeiso"
    update: true
    clone: true
    force: true

- name: update permissions
  file:
    path: "{{git.directory}}/makeiso"
    mode: 0777
    recurse: true

- name: configure variables
  stat:
    path: "{{git.directory}}/makeiso/ubuntu-18.04-netboot-amd64-unattended.iso"
  register: iso_exists

- name: generate kickstart image
  when: iso_exists == false
  shell: ./ubuntu/18.04/build-iso.sh
  become: false
  args:
    chdir: "{{git.directory}}/makeiso"
    executable: /bin/bash

