---
- name: "configure nfs mount"
  include_role:
    name: fiehnlab-utils/nfs-mount-init
  tags:
    - deploy_msflo

- name: "deploying MS-FLO"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: msflo
    compose: "{{git.remote_directory}}/msflo/docker-compose-nfs.yml"
  environment:
    NFS_HOST: "{{nfs.host}}"
    NFS_PATH: "/mnt/{{nfs_cluster}}/{{nfs_dir}}"

  tags:
    - deploy_msflo