---
- name: "configure nfs mount"
  include_role:
    name: fiehnlab/nfs-mount-init
  vars:
    mount: test
    dir: jenkins
  tags:
    - deploy_jenkins

- name: "deploying Jenkins"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: jenkins
    compose: "{{git.remote_directory}}/jenkins-dind/docker-compose.yml"
  tags:
    - deploy_jenkins

