---
- name: "configure nfs mount"
  include_role:
    name: fiehnlab-utils/nfs-mount-init
  tags:
    - deploy_jenkins

- name: "deploying Jenkins"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: jenkins
    compose: "{{git.remote_directory}}/jenkins-dind/docker-compose.yml"
  environment:
    MNT_HOST: "{{nfs.host}}"
    MNT_PATH: "/mnt/{{nfs_cluster}}/{{nfs_dir}}"
  tags:
    - deploy_jenkins
