##
# configures the virtual machines for this group
# which require to be created and deployed on each node
#
virtual_machines:
  - machine:
    name: test
    cpus: 1
    memory: 8192
    storage_size: 20
    network: br31
    pool: nvme


##
# defines the network configuration for all nodes. Can also be done on the host level if you have different hardware setups
#
# this configuration is based on a HP Proliant G7, with 4 onboard network cards
# and 2 additional 10GB networks cards
# utilizing a default VLAN
# and a couple of custom ones. The KVM's will run on the defined bridges! So these are required
#
network:
  netplan:
    configuration:
      network:
        ethernets:
          enp3s0f0: {}
          enp3s0f1: {}
          enp4s0f0: {}
          enp4s0f1: {}
          ens2f0:
            dhcp4: true
          ens2f1: {}

        bonds:
          bond0:
            parameters:
              mode: 802.3ad
              lacp-rate: fast
              mii-monitor-interval: 50
            interfaces:
              - enp3s0f0
              - enp3s0f1
              - enp4s0f0
              - enp4s0f1
            mtu: 9000
        vlans:
          # delegate to the bridges
          vlan.30:
            id: 30
            link: bond0
            dhcp4: false
            dhcp6: false

          # delegate to the bridges
          vlan.31:
            id: 31
            link: bond0
            dhcp4: false
            dhcp6: false


          # host only
          vlan.110:
            id: 110
            link: ens2f0
            dhcp4: false
            dhcp6: false


          # host only
          vlan.111:
            id: 111
            link: ens2f0
            dhcp4: false
            dhcp6: false


        # defines brigdes for KVM based interfaces
        bridges:

          # production cluster resides in this network
          br30:
            interfaces:
              - vlan.30
            dhcp6: false
            dhcp4: true
            dhcp-identifier: mac

          # test cluster resides in this network
          br31:
            interfaces:
              - vlan.31
            dhcp4: true
            dhcp6: false
            dhcp-identifier: mac

          # dedicated data lan for fast access
          # based on NVM storage
          br110:
            interfaces:
              - vlan.110
            dhcp6: false
            dhcp4: true
            dhcp-identifier: mac

          # dedicated data lan for nas shares
          # based on a dedicated storage box
          br111:
            interfaces:
              - vlan.111
            dhcp4: true
            dhcp6: false
            dhcp-identifier: mac


##
# system wide python interpreter
ansible_python_interpreter: /usr/bin/python3

##
# defines all user accounts we want to setup
accounts:
  users:
    - name: "wohlgemuth"
      ssh_keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZKJzrqCjPtHep4JT/qefyKtS9SKhhxlxq/VMkz3jN7QdF/2JEpU3t4omMAtR1f/TCRz3GOMU+JiqUlKM5mYbx31yQfZ75WM7wbkhXVFBSswalYgVmJqaQ1rdqkARxN8TxkLVwtuRJq2ggDIUZCQ8ux9rSQqIOnQNPO7jmFrSg/ZbtwYNePrz/RKS7Kbl/f5g/K1Ea2x4XTcAad5JD6Nq1Pb2Mlq5hxGYjtd0KDAyWT+W4usvFBkoejHA2Mpvr9jAerve0ej7siehPzjQvsQKMpWyE8/xrTTHW2RFAAEJjGhJkK2prJ8L3EeGldQK1K1bUfuDVzuM76nhm3fj4PPYz wohlgemuth@blade"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClOW+HSEzQrNaAxFvOiTagcu/DfRBWawLp/9BTWHi4owtb72AcNxp/pyRCODDUmLezTUItpF39weH24+X+iW/ZzcIUBbUl6zVARJbjDbT+/RTaT5zsSFBZuhYWa/ivHcGiV9TWQ2HPsvckP66A4FMe+TSkcUrJrjRUVIEGHQvpvG9jDo0I88NYq+M6QVQTN+AXCxr3GNqjbbINVhOhRoyP/ZBB8eonL/KlVJpqwLkdMMj4BRKLcU+rq3Ql9ugdp/6OHbmLK4hvE1dtUPOQHPLN1fJvcLO+vjiVEXJW10tc4caBmUeufFfHhomvk8Da7TCP5mX/96CzJNOOfRSLwUvF wohlgemuth@test-ansible-1"
##
# this is the default key to be used to install all virtual machines
#
vm_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZKJzrqCjPtHep4JT/qefyKtS9SKhhxlxq/VMkz3jN7QdF/2JEpU3t4omMAtR1f/TCRz3GOMU+JiqUlKM5mYbx31yQfZ75WM7wbkhXVFBSswalYgVmJqaQ1rdqkARxN8TxkLVwtuRJq2ggDIUZCQ8ux9rSQqIOnQNPO7jmFrSg/ZbtwYNePrz/RKS7Kbl/f5g/K1Ea2x4XTcAad5JD6Nq1Pb2Mlq5hxGYjtd0KDAyWT+W4usvFBkoejHA2Mpvr9jAerve0ej7siehPzjQvsQKMpWyE8/xrTTHW2RFAAEJjGhJkK2prJ8L3EeGldQK1K1bUfuDVzuM76nhm3fj4PPYz wohlgemuth@blade"

