ansible_python_interpreter: /usr/bin/python3

# defines all user accounts we want to setup
accounts:
  users:
    - name: "wohlgemuth"
      admin: true
      ssh_keys:
        - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
