##
# configures the virtual machines for this group
# which require to be created and deployed on each node
#
virtual_machines:

  - machine:
    name: test-2x4
    cpus: 2
    memory: 4096
    storage_size: 80000
    network:
      - br.test
    pool: nvme
    group: test_cluster
    domain: test.fiehnlab.ucdavis.edu
    manager_possible: true # possible to be a manager, if running on a manager node

  - machine:
    name: prod-16x16
    cpus: 16
    memory: 16384
    storage_size: 160000
    network:
      - br.prod
    pool: nvme
    group: prod_cluster
    domain: cluster.fiehnlab.ucdavis.edu
    manager_possible: false # possible to be a manager, if running on a manager node

  - machine:
    name: prod-4x8
    cpus: 4
    memory: 8192
    storage_size: 160000
    network:
      - br.prod
    pool: nvme
    group: prod_cluster
    domain: cluster.fiehnlab.ucdavis.edu
    manager_possible: true # possible to be a manager, if running on a manager node

  - machine:
    name: dev-4x16
    cpus: 4
    memory: 16384
    storage_size: 160000
    network:
      - br.dev
    pool: nvme
    group: dev_cluster
    domain: dev.fiehnlab.ucdavis.edu
    manager_possible: true # possible to be a manager, if running on a manager node

##
# vm authorization settings
#
vm_authorization:

  ##
  # this is your root password hash, which should never be checked into git
  #  mkpasswd -m sha-512
  #
  # and utilized for all the KVMS
  root_passwd_hash: $6$3kIBSa.Cn$LGGcnq4WklBpWsmBCkALocO.ZnrutkkLmrs1YFQurFxXB9RMhGXbBisM94NMRhHiJpBGae0.tOOGUYlVxLQUf0

##
# default configurations of things we want to have deployed
# on the KVM nodes
docker:

  ##
  # which fork do you want to use for swarmprom
  swarmprom:
    repo:  https://github.com/metabolomics-us/swarmprom.git
    deploy: true

  ##
  # which fork do you want to use for the elk logstash
  elk:
    repo: https://github.com/metabolomics-us/wcms-cluster-elk.git
    deploy: true


  nic: ens2f0
