---
- name: "deploying MIDA"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: mida
    compose: "{{git.remote_directory}}/mida/docker-compose.yml"
  tags:
    - deploy_mida
