---
- name: "deploying MoNA"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: mona
    compose: "{{git.remote_directory}}/mona/docker-compose-stack-megamona.yml"
  tags:
    - deploy_mona
