
- name: "be the vim with you {{ username }}!"
  become_user: "{{ username }}"
  shell: "curl -sLf https://spacevim.org/install.sh | bash"
  warn: false
  args:
    executable: /bin/bash
  tags:
    spacevim
