- apt:
    name: [curl, vim]
    state: present

- name: "be the vim with you {{ username }}!"
  become_user: "{{ username }}"
  shell: "curl -sLf https://spacevim.org/install.sh | bash"
  args:
    warn: false
    executable: /bin/bash
  tags:
    - spacevim
