- set_fact:
    home_path: "/home/{{username}}"

- name: Install tmux and git
  apt: name={{ item }} state=present
  with_items:
    - tmux
    - git
  when: install
  become: true

- name: Enable history sharing in .bashrc
  become_user: "{{username}}"
  lineinfile: dest="{{ home_path }}/.bashrc" state=present line={{ item }}
  with_items:
    - export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
  when: share_history

- name: Enable aliases .bashrc
  become_user: "{{username}}"
  lineinfile: dest="{{ home_path }}/.bashrc" state=present line={{ item }}
  with_items:
    - alias tl='tmux ls'
    - alias ta='tmux attach -t'
    - alias tk='tmux kill-session -t'
  when: aliases


- name: Install tmux plugin manager
  become_user: "{{username}}"
  git: repo=https://github.com/tmux-plugins/tpm dest="{{ home_path }}/.tmux/plugins/tpm" update=yes
  when: tmux_plugin_manager

- name: Copy over .tmux.conf
  become_user: "{{username}}"
  template:
    src: ".tmux.conf.j2"
    dest: "{{home_path}}/.tmux.conf"