---
- name: "deploying CDN"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: cdn
    compose: "{{git.remote_directory}}/cdn/docker-compose.yml"
  tags:
    - deploy_cdn
