- name: install pgsql requirement
  when:
    - "'docker_swarm_manager' in group_names"
  apt: name=python3-psycopg2 state=present
  become: true

# Requires the nfs_cluster and nsf_dir vars to be set in the playbook task definition
- name: "configure nfs mount"
  include_role:
    name: fiehnlab-utils/nfs-mount-init
  tags:
    - deploy_docker_registry

- name: "deploy postgress for MSMS storage"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_swarm_service:
    name: msmspg
    image: postgres:9
    state: present
    mounts:
    - type: volume
      target: /var/lib/postgresql/data
      source: msmspg_data
      driver_config:
        name: local
        options:
          type: nfs
          device: ":/mnt/{{nfs_cluster}}/{{nfs_dir}}"
          o: "addr={{nfs.host}},nolock,soft,rw"
    replicas: 1
    env:
      POSTGRES_USER: "{{ msms_db_user }}"
      POSTGRES_DB: "{{ msms_db_name }}"
      POSTGRES_PASSWORD: test

- name: create msms db
  when:
    - "'docker_swarm_manager' in group_names"
  postgresql_db:
    name: "{{ msms_db_name }}"
    login_user: "{{ msms_db_user }}"
    login_host: manager1
    login_password: test
    state: present
