---
- name: "deploying MiniX"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: minix
    compose: "{{git.remote_directory}}/minix/docker-compose.yml"
  tags:
    - deploy_minix
