- name: "cloning logging stack"
  when:
    - "'docker_swarm_manager' in group_names"
    - "elk.deploy == true"
  tags:
    - deploy_logging
  git:
    repo: "{{elk.repo}}"
    version: master
    dest: "{{git.directory}}/logging"
    clone: true
    update: true
  retries: 30
  delay: 10
  register: result
  until: result|succeeded

- name: "configure max map count for elastic"
  when:
    - "'docker_swarm_manager' in group_names"
    - "elk.deploy == true"
    -
  sysctl:
    name: 'vm.max_map_count'
    value: 400000
    sysctl_set: yes
    state: present
    reload: yes
  become: true
  tags:
    - deploy_logging

- name: "configure nfs mount"
  when:
    - "elk.deploy == true"
  include_role:
    name: fiehnlab-utils/nfs-mount-init
  tags:
    - deploy_logging

- name: "undeploying logging stack"
  when:
    - "'docker_swarm_manager' in group_names"
    - "elk.deploy == true"
  docker_stack:
    absent_retries: 100
    state: absent
    name: logging
    compose: "{{git.directory}}/logging/docker-stack-nfs.yml"
  environment:
    NFS_HOST: "{{nfs.host}}"
    NFS_PATH: "/mnt/{{nfs_cluster}}/{{nfs_dir}}"
  tags:
    - deploy_logging

- name: "deploying logging stack"
  when:
    - "'docker_swarm_manager' in group_names"
    - "elk.deploy == true"
  docker_stack:
    state: present
    name: logging
    compose: "{{git.directory}}/logging/docker-stack-nfs.yml"
  environment:
    NFS_HOST: "{{nfs.host}}"
    NFS_PATH: "/mnt/{{nfs_cluster}}/{{nfs_dir}}"
  tags:
    - deploy_logging
