---
- name: "mount the desired nfs folder"
  when:
    - "'docker_swarm_manager' in group_names"
  mount:
    path: /mnt/nfs
    src: "nas1.nas.fiehnlab.ucdavis.edu:/mnt/{{nfs_cluster}}"
    fstype: nfs
    state: mounted
  tags:
    -nfs

- name: "create service folder on nfs mount"
  when:
    - "'docker_swarm_manager' in group_names"
  file:
    path: "/mnt/nfs/{{nfs_dir}}"
    state: directory
  tags:
    -nfs

- name: "create subdirectories if specified"
  when:
    - "'docker_swarm_manager' in group_names"
    - subdirectories is defined
  file:
    path: "/mnt/nfs/{{nfs_dir}}/{{item}}"
    state: directory
  with_items: "{{subdirectories}}"
  tags:
    -nfs

- name: "create placeholder file to enable nfs mounting from docker"
  when:
    - "'docker_swarm_manager' in group_names"
  file:
    path: "/mnt/nfs/{{nfs_dir}}/.docker"
    state: touch
  tags:
    -nfs

- name: "create placeholder files for subdirectories if specified"
  when:
    - "'docker_swarm_manager' in group_names"
    - subdirectories is defined
  file:
    path: "/mnt/nfs/{{nfs_dir}}/{{item}}/.docker"
    state: touch
  with_items: "{{subdirectories}}"
  tags:
    -nfs

- name: "unmount nfs folder"
  when:
    - "'docker_swarm_manager' in group_names"
  mount:
    path: /mnt/nfs
    state: absent
  tags:
    -nfs
