---
- name: "deploying ClassyFire Batch"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: cfb
    compose: "{{git.remote_directory}}/cfb/docker-compose.yml"
  tags:
    - deploy_cfb
