---
- name: "deploying CTS"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: cts
    compose: "{{git.remote_directory}}/cts/docker-compose.yml"
  tags:
    - deploy_cts
