---
- name: "deploying Eureka"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: eureka
    compose: "{{git.remote_directory}}/eureka/docker-compose.yml"
  tags:
    - deploy_eureka
