##
network:

  ##
  # this contains the general network configuration, which should be adapted to local host needs
  netplan:
    configuration:
      network:
        ethernets:
          enp3s0f0: {}
          enp3s0f1: {}
          enp4s0f0: {}
          enp4s0f1: {}

          ##
          # cluster internal network
          ens2f0:
            dhcp4: true

          ens2f1:
            dhcp4: false

        bonds:
          bond0:
            parameters:
              mode: 802.3ad
              lacp-rate: fast
              mii-monitor-interval: 50
            interfaces:
              - enp3s0f0
              - enp3s0f1
              - enp4s0f0
              - enp4s0f1
            mtu: 9000
            dhcp4: false

        vlans:
          # delegate to the bridges
          vlan.prod:
            id: 30
            link: bond0
            dhcp4: false
            dhcp6: false

          # delegate to the bridges
          vlan.test:
            id: 31
            link: bond0
            dhcp4: false
            dhcp6: false

          # delegate to the bridges
          vlan.nas:
            id: 111
            link: ens2f0
            dhcp4: false
            dhcp6: false

          # delegate to the bridges
          vlan.nvme:
            id: 110
            link: ens2f0
            dhcp4: false
            dhcp6: false
          vlan.dev:
            id: 32
            link: bond0
            dhcp4: false
            dhcp6: false

        # defines brigdes for KVM based interfaces
        bridges:

          # production cluster resides in this network
          br.prod:
            interfaces:
              - vlan.prod
            dhcp6: false
            dhcp4: false
            dhcp-identifier: mac
            addresses:
              - 192.168.30.25/24
          br.dev:
            interfaces:
              - vlan.dev
            dhcp4: false
            dhcp6: false
            dhcp-identifier: mac
            addresses:
              - 192.168.32.25/24


          # test cluster resides in this network
          br.test:
            interfaces:
              - vlan.test
            dhcp4: false
            dhcp6: false
            dhcp-identifier: mac
            addresses:
              - 192.168.31.25/24
          # shared services reside in this network
          br.nvme:
            interfaces:
              - vlan.nvme
            dhcp4: false
            dhcp6: false
            dhcp-identifier: mac
            addresses:
              - 192.168.110.25/24

          # data access resides in this network
          br.nas:
            interfaces:
              - vlan.nas
            dhcp4: false
            dhcp6: false
            dhcp-identifier: mac
            addresses:
              - 192.168.111.25/24
