- name: "install | ssshuttle"
  become: true
  apt:
    name: [sshuttle]

- debug:
    var: sshuttle
- name: "configure aliases | sshuttle"
  lineinfile:
    dest=/home/{{route.owner}}/.bashrc
    line="alias {{route.alias}}='sshuttle -r {{route.gateway}} -vv {{route.destination}}'"
    regexp="^alias {{route.alias}}='sshuttle -r {{route.gateway}} -vv {{route.destination}}'$"
    state=present
    insertafter=EOF
    create=True

  loop: "{{sshuttle}}"
  loop_control:
    loop_var: route