---
- name: "deploying Blood Exposome Database"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: exposome
    compose: "{{git.remote_directory}}/exposome/docker-compose.yml"
  tags:
    - deploy_exposome
