---
- name: "deploying BinView"
  when:
    - "'docker_swarm_manager' in group_names"
  docker_stack:
    state: present
    name: binview
    compose: "{{git.remote_directory}}/binview/docker-compose.yml"
  tags:
    - deploy_binview
