---
- name: "remove temporary git store"
  file:
    dest: "{{git.local_directory}}"
    state: absent
  tags:
    - docker_swarm_repository

- name: "cloning fiehnlab cluster repository locally"
  git:
    repo: "{{git.repo}}"
    dest: "{{git.local_directory}}"
    version: "{{git.branch}}"
    accept_hostkey: true
  tags:
    - docker_swarm_repository
